# Generated by Django 4.2.4 on 2023-08-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student1_remove_book_category_delete_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='year',
            field=models.IntegerField(),
        ),
    ]
